server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
lrh:
  name: 李瑞豪
  age: 23
  sex: 男
  id: 123
  password: 123
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?charset=UTF-8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
mybatis:
  type-aliases-package: com.seven.pojo